from __future__ import annotations
import argparse
from pathlib import Path
import pandas as pd
from trend_following_analyzer import load_config,screen_date
from trend_following_analyzer.rule_catalog import rule_catalog_rows

def main()->None:
    parser=argparse.ArgumentParser(description="Independent trend-following screener for Korean equities"); parser.add_argument("--date"); parser.add_argument("--top-n",type=int,default=None); parser.add_argument("--config",default="config/default.yaml"); parser.add_argument("--universe-xlsx",default=None); parser.add_argument("--out",default="results"); args=parser.parse_args(); base_dir=Path(__file__).resolve().parent; cfg=load_config(base_dir/args.config); resolved,results=screen_date(cfg,scan_date=args.date,top_n=args.top_n,base_dir=base_dir,universe_xlsx=args.universe_xlsx); df=pd.DataFrame([r.to_dict() for r in results]); out_dir=base_dir/args.out/resolved; out_dir.mkdir(parents=True,exist_ok=True); encoding=cfg.get("output",{}).get("encoding","utf-8-sig"); all_path=out_dir/"stage_market_screen.csv"; legacy_path=out_dir/"stage_screen.csv"; stage2_path=out_dir/"stage2_candidates.csv"; core_path=out_dir/"lecture_core_candidates.csv"; breadth_path=out_dir/"market_breadth_summary.csv"; intraday_path=out_dir/"market_intraday_summary.csv"; rs_path=out_dir/"relative_strength_summary.csv"; rule_path=out_dir/"rule_catalog.csv"; df.to_csv(all_path,index=False,encoding=encoding); df.to_csv(legacy_path,index=False,encoding=encoding); pd.DataFrame(rule_catalog_rows()).to_csv(rule_path,index=False,encoding=encoding)
    if df.empty:
        for p in [stage2_path,core_path,breadth_path,intraday_path,rs_path]: pd.DataFrame().to_csv(p,index=False,encoding=encoding)
    else:
        df[df["stage"].eq("STAGE_2")].to_csv(stage2_path,index=False,encoding=encoding); df[df["lecture_core_pass"].eq(True)].to_csv(core_path,index=False,encoding=encoding); rs_cols=["ticker","name","market","trading_value_rank","rs_status","rs_measurement","rs_percentile_scope","stock_return_20d_pct","benchmark_return_20d_pct","rs_20d_pct","stock_return_60d_pct","benchmark_return_60d_pct","rs_60d_pct","rs_percentile_20d","rs_percentile_60d","rs_percentile_composite","rs_label","rs_experimental_20d_outperform_pass","rs_experimental_60d_outperform_pass","rs_experimental_percentile_pass","rs_filter_applied"]; df[rs_cols].sort_values(["rs_percentile_composite","trading_value_rank"],ascending=[False,True],na_position="last").to_csv(rs_path,index=False,encoding=encoding)
        breadth_cols=[c for c in df.columns if c=="market" or c.startswith("market_breadth_") or c.startswith("market_new_high_") or c.startswith("market_new_low_") or c=="market_new_high_low_spread"]; df[breadth_cols].drop_duplicates("market").to_csv(breadth_path,index=False,encoding=encoding); intraday_cols=[c for c in df.columns if c=="market" or c.startswith("market_intraday_") or c.startswith("market_gap_") or c.startswith("market_open_close_") or c.startswith("market_close_location_") or c.startswith("market_recovery_") or c.startswith("market_fade_") or c.startswith("market_weak_open_") or c.startswith("market_strong_open_") or c.startswith("market_strong_close_") or c.startswith("market_weak_close_") or c.startswith("market_experimental_intraday_")]; df[intraday_cols].drop_duplicates("market").to_csv(intraday_path,index=False,encoding=encoding)
    print(f"\nTrendFollowingAnalyzer | {resolved} | Phase 1-5"); print("Relative Strength: BACKTEST_ONLY (20D/60D + same-market percentile)")
    if not df.empty:
        view=df[["ticker","name","market","rs_label","rs_20d_pct","rs_60d_pct","rs_percentile_composite","rs_experimental_percentile_pass"]].sort_values("rs_percentile_composite",ascending=False,na_position="last"); print("\n[RELATIVE STRENGTH - BACKTEST ONLY]"); print(view.head(30).to_string(index=False))
    for p in [all_path,stage2_path,core_path,breadth_path,intraday_path,rs_path,rule_path]: print(f"[DONE] {p}")
if __name__=="__main__": main()
