from __future__ import annotations

"""Combined-workflow adapter for DynamicChartAnalyzer range backtests.

The canonical main_range.py remains unchanged. This adapter injects the shared
liquidity-union Excel and point-in-time membership generated by the root workflow,
then reuses the exact same V2.2 score_long_events implementation.
"""

import os
from pathlib import Path

import pandas as pd

import main_range


def _ticker(value) -> str:
    text = str(value or "").strip()
    if text.endswith(".0"):
        text = text[:-2]
    return text.zfill(6) if text else ""


def _load_membership(path: str | None) -> pd.DataFrame:
    if not path:
        return pd.DataFrame()
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Dynamic shared membership CSV not found: {p}")
    m = pd.read_csv(p, encoding="utf-8-sig", dtype={"ticker": str})
    required = {"date", "ticker"}
    missing = required - set(m.columns)
    if missing:
        raise ValueError(f"Dynamic membership columns missing: {sorted(missing)}")
    m = m.copy()
    m["signal_date"] = pd.to_datetime(m["date"], errors="coerce").dt.normalize()
    m["ticker"] = m["ticker"].map(_ticker)
    m = m.dropna(subset=["signal_date"])
    keep = ["signal_date", "ticker"]
    for col in ("source_rank", "avg_trading_value_20d"):
        if col in m.columns:
            keep.append(col)
    return m[keep].drop_duplicates(["signal_date", "ticker"], keep="last")


def _install_shared_membership(membership: pd.DataFrame) -> None:
    if membership.empty:
        return

    original_add_rs_percentiles = main_range.add_rs_percentiles
    original_score_long_events = main_range.score_long_events
    eligible_index = pd.MultiIndex.from_frame(membership[["signal_date", "ticker"]])

    def add_rs_percentiles_point_in_time(panel: pd.DataFrame) -> pd.DataFrame:
        if panel is None or panel.empty:
            return original_add_rs_percentiles(panel)
        x = panel.copy()
        x["signal_date"] = pd.to_datetime(x["signal_date"], errors="coerce").dt.normalize()
        x["ticker"] = x["ticker"].map(_ticker)
        idx = pd.MultiIndex.from_frame(x[["signal_date", "ticker"]])
        x = x[idx.isin(eligible_index)].copy()
        return original_add_rs_percentiles(x)

    def score_long_events_point_in_time(
        events: pd.DataFrame,
        confirmed_score: float = 70.0,
        watch_score: float = 55.0,
    ) -> pd.DataFrame:
        if events is None or events.empty:
            return original_score_long_events(
                events,
                confirmed_score=confirmed_score,
                watch_score=watch_score,
            )
        x = events.copy()
        x["signal_date"] = pd.to_datetime(x["signal_date"], errors="coerce").dt.normalize()
        x["ticker"] = x["ticker"].map(_ticker)
        idx = pd.MultiIndex.from_frame(x[["signal_date", "ticker"]])
        x = x[idx.isin(eligible_index)].copy()
        if x.empty:
            return original_score_long_events(
                x,
                confirmed_score=confirmed_score,
                watch_score=watch_score,
            )

        rank_cols = ["signal_date", "ticker"]
        extras = []
        if "source_rank" in membership.columns:
            extras.append("source_rank")
        if "avg_trading_value_20d" in membership.columns:
            extras.append("avg_trading_value_20d")
        if extras:
            m = membership[rank_cols + extras].copy()
            rename = {"source_rank": "_membership_source_rank"}
            x = x.merge(m.rename(columns=rename), on=rank_cols, how="left", validate="many_to_one")
            if "_membership_source_rank" in x.columns:
                x["source_rank"] = pd.to_numeric(x["_membership_source_rank"], errors="coerce").fillna(
                    pd.to_numeric(x.get("source_rank"), errors="coerce")
                )
                x = x.drop(columns="_membership_source_rank")

        return original_score_long_events(
            x,
            confirmed_score=confirmed_score,
            watch_score=watch_score,
        )

    main_range.add_rs_percentiles = add_rs_percentiles_point_in_time
    main_range.score_long_events = score_long_events_point_in_time


def main() -> int:
    args = main_range.build_parser().parse_args()

    shared_excel = os.environ.get("LIQUIDITY_UNIVERSE_XLSX", "").strip()
    membership_csv = os.environ.get("LIQUIDITY_MEMBERSHIP_CSV", "").strip()

    if shared_excel:
        shared_path = Path(shared_excel)
        if not shared_path.exists():
            raise FileNotFoundError(f"Dynamic shared universe Excel not found: {shared_path}")
        main_range.KJB_INFO_EXCEL = shared_path
        args.top_n = 0
        args.sort_by = "trading_value"
        print(f"[INFO] Dynamic combined universe: {shared_path}")
        print("[INFO] Dynamic combined mode: analyze shared union; classify only point-in-time members")

    membership = _load_membership(membership_csv)
    if not membership.empty:
        _install_shared_membership(membership)
        print(
            f"[INFO] Dynamic membership: {membership['signal_date'].nunique()} trading days / "
            f"{membership['ticker'].nunique()} union tickers"
        )

    # Avoid ETF authentication for market context. load_pykrx recognizes these as
    # KRX index codes and uses get_index_ohlcv_by_date.
    main_range.BENCHMARK_PROXY = {"KOSPI": "1001", "KOSDAQ": "2001"}

    return main_range.run_range(args)


if __name__ == "__main__":
    raise SystemExit(main())
